# .goreleaser.yml
version: 2
project_name: synolintology143

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: synolintology143
    # The name of the binary file that gets created.
    binary: synolintology143
    # Path to the main.go file.
    main: ./cmd/synolintology143/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    # Make GOAMD64 explicit so dist folder names are stable (linux_amd64_v1)
    goamd64:
      - v1
    # Make GOARM64 explicit so dist folder names are stable (linux_arm64_v8.0)
    goarm64:
      - v8.0

# "Entware-style" install
archives:
  - id: archives
    # Sets the name like: synolintology143_1.0.0_linux_amd64.tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    formats: [tar.gz]
    # Include the license and README in the archive for good vibes.
    files:
      - LICENSE
      - README.md

# nfpm to create native Debian packages (.deb).
nfpms:
  - id: debs
    package_name: synolintology143
    vendor: 'goura'
    homepage: 'https://github.com/goura/synolintology143'
    maintainer: 'Goura <goura@example.com>'
    description: A CLI tool to find filenames that violate the Synology eCryptfs 143-byte limit.
    license: MIT
    formats:
      - deb
    # Install binary under /opt/bin to match Entware usage.
    bindir: /opt/bin
    # Use build IDs defined in the 'builds' section above.
    ids:
      - synolintology143

  - id: ipks
    package_name: synolintology143
    vendor: 'goura'
    homepage: 'https://github.com/goura/synolintology143'
    maintainer: 'Goura <goura@example.com>'
    description: A CLI tool to find filenames that violate the Synology eCryptfs 143-byte limit.
    license: MIT
    formats:
      - ipk
    bindir: /opt/bin
    # Use Entware-style arch labels in filename and control field.
    file_name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Arch "amd64" }}x64-3.2
      {{- else if eq .Arch "arm64" }}aarch64-3.10
      {{- else }}{{ .Arch }}{{ end }}
    # IPK packager-specific settings.
    ipk:
      fields:
        Architecture: >-
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "arm64" }}aarch64
          {{- else }}{{ .Arch }}{{ end }}
        Section: utils
        Priority: optional
    ids:
      - synolintology143

# changelog from git commit messages.
changelog:
  sort: asc
  filters:
    # Exclude boring commits from the changelog.
    exclude:
      - '^doc:'
      - '^docs:'
      - '^test:'
      - '^tests:'
      - '^ci:'
      - 'Merge pull request'
      - 'Merge branch'
