name: Release synolintology143

on:
  push:
    branches:
      - main
    # Run the workflow on tag pushes so GoReleaser can publish releases
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test -v ./...

  release:
    name: Release
    runs-on: ubuntu-latest
    # only runs when a tag is pushed
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Fetch all history so GoReleaser can generate a clean changelog.
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify release binaries exist
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ls -la dist
          test -f dist/synolintology143_linux_amd64/synolintology143
          test -f dist/synolintology143_linux_arm64/synolintology143

      - name: Build IPK (amd64) in Alpine
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          docker run --rm -v "$PWD":/work -w /work alpine:edge /bin/sh -ceu '
            apk add --no-cache \
              --repository https://dl-cdn.alpinelinux.org/alpine/edge/main \
              --repository https://dl-cdn.alpinelinux.org/alpine/edge/community \
              --repository https://dl-cdn.alpinelinux.org/alpine/edge/testing \
              python3 opkg-utils >/dev/null
            sh scripts/build-ipk.sh dist/synolintology143_linux_amd64/synolintology143 "${TAG_NAME}" linux_amd64 synolintology143
          '

      - name: Build IPK (arm64) in Alpine
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          docker run --rm -v "$PWD":/work -w /work alpine:edge /bin/sh -ceu '
            apk add --no-cache \
              --repository https://dl-cdn.alpinelinux.org/alpine/edge/main \
              --repository https://dl-cdn.alpinelinux.org/alpine/edge/community \
              --repository https://dl-cdn.alpinelinux.org/alpine/edge/testing \
              python3 opkg-utils >/dev/null
            sh scripts/build-ipk.sh dist/synolintology143_linux_arm64/synolintology143 "${TAG_NAME}" linux_arm64 synolintology143
          '

      - name: Upload IPK assets to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/*.ipk
          fail_on_unmatched_files: true
