name: Release synolintology143

on:
  push:
    branches:
      - main
    # Run the workflow on tag pushes so GoReleaser can publish releases
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test -v ./...

  release:
    name: Release
    runs-on: ubuntu-latest
    # only runs when a tag is pushed
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # Fetch all history so GoReleaser can generate a clean changelog.
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install packaging tools
        run: sudo apt-get update && sudo apt-get install -y opkg-utils

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
